[package]
name = "tree-sitter-graph"
version = "0.0.1"
description = "Construct graphs from parsed source code"
homepage = "https://github.com/tree-sitter/tree-sitter-graph/"
repository = "https://github.com/tree-sitter/tree-sitter-graph/"
readme = "README.md"
license = "MIT OR Apache-2.0"
authors = [
  "Douglas Creager <dcreager@dcreager.net>"
]
edition = "2018"

[lib]
# All of our tests are in the tests/it "integration" test executable.
test = false

[dependencies]
regex = "1"
thiserror = "1.0"
tree-sitter = "0.19"

[dependencies.string-interner]
version = "0.12"
default-features = false
features = ["std", "inline-more", "backends"]

[dev-dependencies]
tree-sitter-python = "0.19"
