name: Publish on crates.io

on:
  push:
    tags:
      - v*'

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust environment
        uses: hecrj/setup-rust-action@v1
      - name: Checkout repository
        uses: actions/checkout@v2
      # TODO Verify the crate version matches the tag
      - name: Verify publish crate
        uses: katyo/publish-crates@v1
        with:
          dry-run: true
      - name: Publish crate
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
