name: Publish release

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  publish-crate:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust environment
        uses: hecrj/setup-rust-action@v1
      - name: Checkout repository
        uses: actions/checkout@v2
      # TODO Verify the crate version matches the tag
      - name: Verify publish crate
        uses: katyo/publish-crates@v1
        with:
          dry-run: true
      - name: Publish crate
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
